# Generated by Django 5.2.4 on 2025-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('INPROGRES', 'In Progres'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
