from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from api.models import Task

# Create your tests here.

class TaskAPITestCase(APITestCase):
    def setUp(self):
        self.task = Task.objects.create(
            title="Sample Task",
            description="Testing the API",
            status="TODO"
        )
        self.list_url = reverse("task-list")   # generated by DefaultRouter
        self.detail_url = reverse("task-detail", args=[self.task.id])

    def test_list_tasks(self):
        response = self.client.get(self.list_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertGreaterEqual(len(response.data), 1)

    def test_create_task(self):
        data = {
            "title": "New Task",
            "description": "Created via test",
            "status": "TODO"
        }
        response = self.client.post(self.list_url, data, format="json")
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Task.objects.count(), 2)

    def test_retrieve_task(self):
        response = self.client.get(self.detail_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["title"], self.task.title)


